### ISSUE TITLE
Calf doesn't compile with fluidsynth 2.0.4 // error: invalid use of incomplete type ‘fluid_sfont_t’ {aka ‘struct _fluid_sfont_t’}

### ISSUE THREAD

**Issue by internethering** [calf-studio-gear/calf#225]
hey, calf 0.90.1 doesn't compile on my gentoo host:

```
fluidsynth.cpp: In member function ‘fluid_synth_t* calf_plugins::fluidsynth_audio_module::create_synth(int&)’:
fluidsynth.cpp:77:33: error: invalid use of incomplete type ‘fluid_sfont_t’ {aka ‘struct _fluid_sfont_t’}
         soundfont_name = (*sfont->get_name)(sfont);
```
see: [build.log](https://github.com/calf-studio-gear/calf/files/3038911/build.log)

fluidsynth 2.0.4 is installed. (cropped) informations about the system:

```
Portage 2.3.62 (python 2.7.16-final-0, default/linux/amd64/17.1/desktop/plasma/systemd, gcc-8.3.0, glibc-2.29-r1, 4.19.25-rt-rt16 x86_64)
=================================================================
System uname: Linux-4.19.25-rt-rt16-x86_64-Intel-R-_Core-TM-_i5-3570T_CPU_@_2.30GHz-with-gentoo-2.6
sh bash 5.0_p3-r1
ld GNU ld (Gentoo 2.31.1 p5) 2.31.1
app-shells/bash:          5.0_p3-r1::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.28.0::gentoo
dev-lang/python:          2.7.16::gentoo, 3.6.8::gentoo, 3.7.3::gentoo
dev-util/cmake:           3.14.1::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/sandbox:         2.17::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.11.6-r3::gentoo, 1.16.1-r1::gentoo
sys-devel/binutils:       2.31.1-r4::gentoo, 2.32::gentoo
sys-devel/gcc:            8.2.0-r6::gentoo, 8.3.0::gentoo
sys-devel/gcc-config:     2.0::gentoo
sys-devel/libtool:        2.4.6-r5::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 5.0-r1::gentoo (virtual/os-headers)
sys-libs/glibc:           2.29-r1::gentoo
ACCEPT_KEYWORDS="amd64 ~amd64"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -march=ivybridge -pipe -fomit-frame-pointer"
CHOST="x86_64-pc-linux-gnu"
CXXFLAGS="-O2 -march=ivybridge -pipe -fomit-frame-pointer"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs candy config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j4"
USE="X a52 aac aacplus acl acpi activities alsa amd64 amr amrenc ao archive audiofile avahi bash-completion berkdb bluetooth branding bzip2 cacert cairo caps cdda cdio cdr cli crypt css cuda cups cxx dbus declarative djvu dmx dri dri3 dssi dts dvd dvdr egl emboss encode exif fam fat fbcon ffmpeg flac fluidsynth fontconfig fortran fuse gdbm gdu geolocation gif gimp glamor gles gles2 gme gmp gnuplot gphoto2 gpm graphviz hddtemp hid iconv icq id3tag idn imagemagick inotify iproute2 iptables ipv6 jack jbig jpeg jpeg2k kde kipi kms kwallet ladish ladspa lame latex lcms libass libcaca libnotify libsamplerate libtirpc lm_sensors lv2 lzma lzo mad matroska midi mmap mng modemmanager mp3 mp4 mpeg mtp multilib musepack ncurses networkmanager nfs nls nptl ogg openal openexr opengl openmp opus oscar pam pango pcre pdf phonon plasma plotutils png policykit postscript ppds projectm pulseaudio qml qt5 rar raw readline realtime samba sbsms scanner sdl sdl-image seccomp semantic-desktop sid sndfile soundtouch speex spell ssl startup-notification suid svg symlink systemd taglib tcpd theora thinkpad threads tiff tremor truetype twolame udev udisks unicode upnp upnp-av upower usb vaapi vamp vdpau vim-syntax vlc vlm vnc vorbis vpx vst wavpack wayland webp widgets wifi wireless wma wma-fixed wmf wxwidgets x264 x265 xattr xcb xcomposite xinerama xml xmp xv xvid xvmc zeroconf zip zlib" ABI_X86="32 64"
CPU_FLAGS_X86="aes avx f16c mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" 
ELIBC="glibc"
```

**Comment by internethering** [comment]
Untill today fluidsynth was installed as version 1.1.11. With this version calf compiles fine.

**Comment by boomshop** [comment]
Was already fixed by @schnitzeltony

**Comment by internethering** [comment]
there is no release with this fix?

**Comment by boomshop** [comment]
Not by now.

**Comment by rugubara** [comment]
> Was already fixed by @schnitzeltony 
@boomshop , can you reference a commit please?

**Comment by trebmuh** [comment]
@rugubara [see here](https://github.com/calf-studio-gear/calf/commits?author=schnitzeltony)

**Comment by internethering** [comment]
It would be really nice to release a fixed version. VLC 3 and Audacious-Plugins 3.10 depends on fluidsynth 2, if you want have support for fluidsynth. This Bug force me to disable fluidsynth support at vlc & audacious...

**Comment by internethering** [comment]
It would be really nice to release a fixed version. VLC 3 and Audacious-Plugins 3.10 depends on fluidsynth 2, if you want have support for fluidsynth. This Bug force me to disable fluidsynth support at vlc & audacious...
