### ISSUE TITLE
analyzer.cpp:473:59: error: no matching function for call to 'max'

### ISSUE THREAD

**Issue by david0** [calf-studio-gear/calf#94]
On Mac compiliation fails since 784c8428c885bc420291de63e0dd7e2839e682bd with errors like

```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -I.. -I. -ffast-math -finline-limit=80 -I/usr/local/Cellar/fluid-synth/1.1.6/include -I/usr/local/Cellar/lv2/1.12.0/include -D_REENTRANT -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -g -O2 -O3 -finline-functions -finline-functions-called-once -Wall -c modules_delay.cpp  -fno-common -DPIC -o .libs/modules_delay.o
analyzer.cpp:473:59: error: no matching function for call to 'max'
                                fft_outL[_iter] = 0.25f * std::max(n * 0.6f * \
                                                          ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2654:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp'
      ('double' vs. 'float')
max(const _Tp& __a, const _Tp& __b)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2646:1: note: candidate function template not viable: requires 3 arguments, but 2 were
      provided
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
```

I'm not sure what is the intention behind this commit, but looking at the [affected line](https://github.com/calf-studio-gear/calf/blob/master/src/analyzer.cpp#L474) tells me that fabs returns double and the other parameter is float (at least with my toolchain). Maybe [fabsf](http://en.cppreference.com/w/c/numeric/math/fabs) should be used here?

**Comment by philipchungtech** [comment]
It seems the commit is for working around header changes in GCC 6, but it breaks other compilers (as you've experienced).

**Comment by asbaklm** [comment]
I'm getting a similarish error on Mint 18 with the master (currently e7daf5503832684d410e1a68bcc11837b1cd158a)

I've switched to the previous commit from 13 August.
https://github.com/calf-studio-gear/calf/commits/master

242c51f1aed2766e01a4d91fe7b09e72cbb1a90a
git checkout -b oldcalf 242c51f1aed2766e01a4d91fe7b09e72cbb1a90a

This compiles ok.

**Comment by jhenkins** [comment]
I have an identical situation on Ubuntu Studio 16.04 (GCC 5.4.0).

Thanks to asbaklm for the tip to check out the previous commit, that does indeed build correctly on GCC 5. In this particular case, the problematic commit does not seem to change anything much from a functional perspective, so I am happy with this work-around for now.

**Comment by trebmuh** [comment]
Hi,

Debian Jessie up-to-date here.

72b13fa build fine. https://github.com/calf-studio-gear/calf/commit/e7daf5503832684d410e1a68bcc11837b1cd158a doesn't (a problem regarding src/analyzer.cpp which looks to be already reported here and as a comment in the commit by @IvanDSM here : https://github.com/calf-studio-gear/calf/commit/e7daf5503832684d410e1a68bcc11837b1cd158a).

Hope that helps.

**Comment by pmjdebruijn** [comment]
I've had this issue on Ubuntu Trusty (14.04) and Xenial (16.04) as well...

Reverse applying e7daf55 on current master resolves the issue for these older compilers.

**Comment by boomshop** [comment]
Should be fixed by f392c5

**Comment by trebmuh** [comment]
I just rebuild from https://github.com/calf-studio-gear/calf/commit/f61c966cfc6ccbb44d9c4e4e9b7f1100bbe728f2 and it's fixed. Thanks @boomshop !

**Comment by boomshop** [comment]
You're welcome, thanks for reporting and testing (to the other reporters as well).
