### ISSUE TITLE
0.90.2 fails to build: no matching member function for call to 'lerp_table_lookup_float_mask'

### ISSUE THREAD

**Issue by yurivict** [calf-studio-gear/calf#227]
The FreeBSD port fails to build:
```
In file included from plugin.cpp:33:
./calf/organ.h:160:19: error: no matching member function for call to 'lerp_table_lookup_float_mask'
        return ph.lerp_table_lookup_float_mask(data, ORGAN_BIG_WAVE_SIZE - 1);
               ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by yurivict** [comment]
@kfoltman Could you please help with this? I can't update the FreeBSD port because of this regression.

**Comment by yurivict** [comment]
0.90.3 still has this problem.
The problem exists when built with clang-8, gcc-8 builds it ok.

Please fix the clang build.

**Comment by kfoltman** [comment]
Which version of clang-8 is it? I can't reproduce this on Linux.

**Comment by yurivict** [comment]
$ c++ -v
FreeBSD clang version 8.0.0 (tags/RELEASE_800/final 356365) (based on LLVM 8.0.0)

**Comment by kfoltman** [comment]
It compiles with version 8.0.1-+rc4-1 and 7.0.1-8 - perhaps 8.0.0 has some bugs/regressions that result in spurious errors.

Meanwhile, I've started trying to fix all the clang-8 warnings. Most are harmless, but I found a few potential bugs or at least things done not exactly right.

**Comment by kfoltman** [comment]
Actually, no, I had an outdated version, without recent changes by Markus.

I can reproduce it now - seems to be a template substitution problem, so might be easy enough to fix.

**Comment by giuliomoro** [comment]
> @kfoltman I just pushed a possible fix for the clang compilation error, plus some easy warning fixes.

Thanks, the latest git head as of today (0f45a436b729e71cc975d82beb4f369026e5db9f) does built with no errors with clang-3.9 on Debian Stretch, while the latest release (0.90.3) fails. A new bugfix release including whatever magic change you made above to fix the build error would be welcome!
